### ISSUE TITLE
Duplicating module when generating a command

### ISSUE THREAD

**Issue by EduardoSimon** [ArkerLabs/event-sourcing-generator#1]
I have a module in my nestjs project already called users. I want to create a command in that module/domain called RegisterUser.

When I generate a command using the following bash command:
`es-generator generate -t command -d users -n RegisterUser`

I get this: 
![image](https://user-images.githubusercontent.com/19764148/75818010-735b5900-5d98-11ea-9616-0df91cf6b543.png)

**Comment by Nytyr** [comment]
You can specify the output folder, where your module/domain is in.

For example:

`es-generator generate -t command -d users -n RegisterUser -o src/`
